<?php

/**
 * @file
 * Contains manifesto_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function manifesto_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the manifesto_core module.
    case 'help.page.manifesto_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides core features for the demo site.') . '</p>';
      return $output;

    default:
  }
}
